magick amerge.png             amerge.xpm
magick arrow_down.png         arrow_down.xpm
magick arrow_up.png           arrow_up.xpm
magick delete-all.png         delete-all.xpm
magick delete.png             delete.xpm
magick Download.png           Download.xpm
magick file-add.png           file-add.xpm
magick folder-open.png        folder-open.xpm
magick lfkc-encoder.png       lfkc-encoder.xpm
magick play.png               play.xpm
magick run.png                run.xpm
magick table_sort_asc.png     table_sort_asc.xpm
magick table_sort_desc.png    table_sort_desc.xpm
magick trash.png              trash.xpm
magick vmerge.png             vmerge.xpm

ren amerge.xpm                  icon_encode_amerge.py
ren arrow_down.xpm              icon_encode_arrow_down.py
ren arrow_up.xpm                icon_encode_arrow_up.py
ren delete-all.xpm              icon_encode_delete_all.py
ren delete.xpm                  icon_encode_delete.py
ren Download.xpm                icon_yutube_download.py
ren file-add.xpm                icon_encode_file_add.py
ren folder-open.xpm             icon_encode_folder_open.py
ren lfkc-encoder.xpm            icon_encoder.py
ren play.xpm                    icon_encode_play.py
ren run.xpm                     icon_run.py
ren table_sort_asc.xpm          icon_encode_table_sort_asc.py
ren table_sort_desc.xpm         icon_table_sort_desc.py
ren trash.xpm                   icon_encode_trash.py
ren vmerge.xpm                  icon_encode_vmerge.py